name: Build and Run Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "helloworld"
  IMAGE_TAG: ${{ github.run_number }}


jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Run Docker Image
        run: docker run -it ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
